-- 1. Liên kết với bảng USERTABLE (Học viên đăng ký)
ALTER TABLE COURSE_ENROLLMENT
ADD CONSTRAINT FK_COURSE_ENROLLMENT_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- 2. Liên kết với bảng COURSE (Khóa học được đăng ký)
ALTER TABLE COURSE_ENROLLMENT
ADD CONSTRAINT FK_COURSE_ENROLLMENT_COURSE
FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID);