-- 1. Liên kết với bảng USERTABLE (Người đánh giá)
ALTER TABLE COURSE_RATING
ADD CONSTRAINT FK_COURSE_RATING_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- 2. Liên kết với bảng COURSE (Khóa học được đánh giá)
ALTER TABLE COURSE_RATING
ADD CONSTRAINT FK_COURSE_RATING_COURSE
FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID);