-- 1. Liên kết với bảng USERTABLE (Người làm bài)
ALTER TABLE EXERCISE_ATTEMPT
ADD CONSTRAINT FK_EXERCISE_ATTEMPT_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- 2. Liên kết với bảng EXERCISE (Bài tập nào)
ALTER TABLE EXERCISE_ATTEMPT
ADD CONSTRAINT FK_EXERCISE_ATTEMPT_EXERCISE
FOREIGN KEY (ExerciseID) REFERENCES EXERCISE(ExerciseID);