-- 1. Liên kết bảng THEORY_LESSON với bảng CHAPTER
ALTER TABLE THEORY_LESSON
ADD CONSTRAINT FK_THEORY_LESSON_CHAPTER
FOREIGN KEY (ChapterID) REFERENCES CHAPTER(ChapterID);

-- 2. Liên kết bảng VIDEO_LESSON với bảng CHAPTER
ALTER TABLE VIDEO_LESSON
ADD CONSTRAINT FK_VIDEO_LESSON_CHAPTER
FOREIGN KEY (ChapterID) REFERENCES CHAPTER(ChapterID);

-- 3. Liên kết bảng EXERCISE với bảng CHAPTER
ALTER TABLE EXERCISE
ADD CONSTRAINT FK_EXERCISE_CHAPTER
FOREIGN KEY (ChapterID) REFERENCES CHAPTER(ChapterID);