-- Liên kết bảng PRACTICE_ATTEMPT_INFO với bảng USERTABLE
ALTER TABLE PRACTICE_ATTEMPT_INFO
ADD CONSTRAINT FK_PRACTICE_ATTEMPT_INFO_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- Liên kết bảng PRACTICE_ATTEMPT_INFO với bảng PRACTICES
ALTER TABLE PRACTICE_ATTEMPT_INFO
ADD CONSTRAINT FK_PRACTICE_ATTEMPT_INFO_PRACTICE
FOREIGN KEY (PracticeID) REFERENCES PRACTICES(PracticeID);
