-- Liên kết bảng TEACHER_EDUCATION với bảng TEACHER
ALTER TABLE TEACHER_EDUCATION
ADD CONSTRAINT FK_TEACHER_EDUCATION_TEACHER
FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID)
ON DELETE CASCADE; -- Tùy chọn: Nếu xóa Giáo viên thì xóa luôn hồ sơ học vấn của họ