-- Liên kết bảng TEST_ATTEMPT_RECORDS với bảng USERTABLE (Người làm bài)
ALTER TABLE TEST_ATTEMPT_RECORDS
ADD CONSTRAINT FK_TEST_ATTEMPT_RECORDS_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- Liên kết bảng TEST_ATTEMPT_RECORDS với bảng TEST (Bài kiểm tra nào)
ALTER TABLE TEST_ATTEMPT_RECORDS
ADD CONSTRAINT FK_TEST_ATTEMPT_RECORDS_TEST
FOREIGN KEY (TestID) REFERENCES TEST(TestID);