USE ElearningDB;
GO
ALTER TABLE ANSWER
ADD CONSTRAINT FK_ANSWER_QUESTION 
FOREIGN KEY (TestID, QuestionNo) REFERENCES QUESTION (TestID, QuestionNo)
ON DELETE CASCADE; -- Tùy chọn: Xóa câu hỏi thì xóa luôn các câu trả lời
-- Liên kết bảng CHAPTER với bảng COURSE
ALTER TABLE CHAPTER
ADD CONSTRAINT FK_CHAPTER_COURSE
FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID);
-- 1. Người viết bình luận
ALTER TABLE COMMENTS
ADD CONSTRAINT FK_COMMENTS_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- 2. Bình luận thuộc về Bài viết (Post)
ALTER TABLE COMMENTS
ADD CONSTRAINT FK_Comments_Post FOREIGN KEY (PostID)
REFERENCES POSTS(PostID);

-- 3. Bình luận thuộc về Khóa học (Course)
ALTER TABLE COMMENTS
ADD CONSTRAINT FK_COMMENTS_COURSE 
FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID);

-- 4. Bình luận trả lời (Reply) - Tham chiếu về chính bảng COMMENTS
-- Vì khóa chính của COMMENTS là cặp (UserID, CreatedAt)
-- Nên khóa ngoại cũng phải tham chiếu đủ cả cặp này
ALTER TABLE COMMENTS
ADD CONSTRAINT FK_COMMENTS_REPLYTOCOMMENTS 
FOREIGN KEY (ReplyUserID, ReplyCreatedAt) REFERENCES COMMENTS(UserID, CreatedAt);





-- 1. Liên kết với bảng USERTABLE (Học viên đăng ký)
ALTER TABLE COURSE_ENROLLMENT
ADD CONSTRAINT FK_COURSE_ENROLLMENT_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- 2. Liên kết với bảng COURSE (Khóa học được đăng ký)
ALTER TABLE COURSE_ENROLLMENT
ADD CONSTRAINT FK_COURSE_ENROLLMENT_COURSE
FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID);
-- Liên kết bảng COURSE với bảng TEACHER (Giáo viên phụ trách)
ALTER TABLE COURSE
ADD CONSTRAINT FK_COURSE_TEACHER
FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID);
-- 1. Liên kết với bảng USERTABLE (Người đánh giá)
ALTER TABLE COURSE_RATING
ADD CONSTRAINT FK_COURSE_RATING_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- 2. Liên kết với bảng COURSE (Khóa học được đánh giá)
ALTER TABLE COURSE_RATING
ADD CONSTRAINT FK_COURSE_RATING_COURSE
FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID);
-- 1. Liên kết với bảng USERTABLE (Người làm bài)
ALTER TABLE EXERCISE_ATTEMPT
ADD CONSTRAINT FK_EXERCISE_ATTEMPT_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- 2. Liên kết với bảng EXERCISE (Bài tập nào)
ALTER TABLE EXERCISE_ATTEMPT
ADD CONSTRAINT FK_EXERCISE_ATTEMPT_EXERCISE
FOREIGN KEY (ExerciseID) REFERENCES EXERCISE(ExerciseID);
-- 1. Liên kết bảng THEORY_LESSON với bảng CHAPTER
ALTER TABLE THEORY_LESSON
ADD CONSTRAINT FK_THEORY_LESSON_CHAPTER
FOREIGN KEY (ChapterID) REFERENCES CHAPTER(ChapterID);

-- 2. Liên kết bảng VIDEO_LESSON với bảng CHAPTER
ALTER TABLE VIDEO_LESSON
ADD CONSTRAINT FK_VIDEO_LESSON_CHAPTER
FOREIGN KEY (ChapterID) REFERENCES CHAPTER(ChapterID);

-- 3. Liên kết bảng EXERCISE với bảng CHAPTER
ALTER TABLE EXERCISE
ADD CONSTRAINT FK_EXERCISE_CHAPTER
FOREIGN KEY (ChapterID) REFERENCES CHAPTER(ChapterID);
-- Liên kết bảng POST với bảng USERTABLE
ALTER TABLE POSTS
ADD CONSTRAINT FK_POSTS_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- Liên kết bảng PRACTICE với bảng TEACHER
ALTER TABLE PRACTICES
ADD CONSTRAINT FK_PRACTICES_TEACHER
FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID);
-- Liên kết bảng PRACTICE_ATTEMPT_INFO với bảng USERTABLE
ALTER TABLE PRACTICE_ATTEMPT_INFO
ADD CONSTRAINT FK_PRACTICE_ATTEMPT_INFO_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- Liên kết bảng PRACTICE_ATTEMPT_INFO với bảng PRACTICES
ALTER TABLE PRACTICE_ATTEMPT_INFO
ADD CONSTRAINT FK_PRACTICE_ATTEMPT_INFO_PRACTICE
FOREIGN KEY (PracticeID) REFERENCES PRACTICES(PracticeID);
ALTER TABLE QUESTION
ADD CONSTRAINT FK_QUESTION_TEST 
FOREIGN KEY (TestID) REFERENCES TEST (TestID)
ON DELETE CASCADE; -- Tùy chọn: Xóa bài kiểm tra thì xóa luôn các câu hỏi bên trong
-- Liên kết bảng TEACHER_EDUCATION với bảng TEACHER
ALTER TABLE TEACHER_EDUCATION
ADD CONSTRAINT FK_TEACHER_EDUCATION_TEACHER
FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID)
ON DELETE CASCADE; -- Tùy chọn: Nếu xóa Giáo viên thì xóa luôn hồ sơ học vấn của họ
-- Liên kết bảng TEACHER với bảng USERTABLE
-- Ý nghĩa: TeacherID chính là UserID. Một người phải là User trước khi được làm Teacher.
ALTER TABLE TEACHER
ADD CONSTRAINT FK_TEACHER_USERTABLE
FOREIGN KEY (TeacherID) REFERENCES USERTABLE(UserID)
ON DELETE CASCADE; -- Tùy chọn: Nếu xóa User thì xóa luôn tư cách Teacher của họ
-- Liên kết bảng TEST_ATTEMPT_RECORDS với bảng USERTABLE (Người làm bài)
ALTER TABLE TEST_ATTEMPT_RECORDS
ADD CONSTRAINT FK_TEST_ATTEMPT_RECORDS_USERTABLE
FOREIGN KEY (UserID) REFERENCES USERTABLE(UserID);

-- Liên kết bảng TEST_ATTEMPT_RECORDS với bảng TEST (Bài kiểm tra nào)
ALTER TABLE TEST_ATTEMPT_RECORDS
ADD CONSTRAINT FK_TEST_ATTEMPT_RECORDS_TEST
FOREIGN KEY (TestID) REFERENCES TEST(TestID);
ALTER TABLE TEST
ADD CONSTRAINT FK_TEST_CHAPTER 
FOREIGN KEY (ChapterID) REFERENCES CHAPTER (ChapterID);
